name: Maven CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Checkstyle Analysis
        run: mvn checkstyle:checkstyle
        continue-on-error: true

      - name: PMD Analysis
        run: mvn pmd:check
        continue-on-error: true

      - name: Generate Coverage Report
        run: mvn jacoco:report

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Maven-Reports
          path: |
            target/site/jacoco/jacoco.xml
            target/checkstyle-result.xml
            target/pmd.xml
