on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: descuentosTDD

    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven 



      - name: Checkstyle Analysis
        run: mvn checkstyle:checkstyle
        continue-on-error: true

      - name: PMD Analysis
        run: mvn pmd:check
        continue-on-error: true

      - name: Generate Coverage Report
        run: mvn jacoco:report

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Maven-Reports
          path: |
            descuentosTDD/target/site/jacoco/jacoco.xml
            descuentosTDD/target/checkstyle-result.xml
            descuentosTDD/target/pmd.xml
